import { View, Text, Image } from '@react-pdf/renderer';
import { sharedPdfStyles as s, MUTED } from './theme';
import type { SignatoryInfo } from './types';

export function PdfBrandHeader({ logoDataUri, title, subtitle }: { logoDataUri: string; title: string; subtitle: string }) {
  return (
    <View style={s.headerRow}>
      <View>
        <Image src={logoDataUri} style={s.logo} />
        <Text style={s.companyName}>AxInfra — Evidence-First Execution Tracking</Text>
      </View>
      <View style={s.titleBlock}>
        <Text style={s.title}>{title}</Text>
        <Text style={s.titleSub}>{subtitle}</Text>
      </View>
    </View>
  );
}

export function MetaItem({ label, value }: { label: string; value: string }) {
  return (
    <View style={s.metaItem}>
      <Text style={s.metaLabel}>{label}</Text>
      <Text style={s.metaValue}>{value || '—'}</Text>
    </View>
  );
}

export function PanelItem({ label, value, full }: { label: string; value: string; full?: boolean }) {
  return (
    <View style={full ? s.panelItemFull : s.panelItem}>
      <Text style={s.panelLabel}>{label}</Text>
      <Text style={s.panelValue}>{value || '—'}</Text>
    </View>
  );
}

export function LabeledBlock({ label, value }: { label: string; value: string }) {
  return (
    <View style={s.labeledBlock}>
      <Text style={s.labeledBlockLabel}>{label}</Text>
      <Text style={s.labeledBlockValue}>{value || '—'}</Text>
    </View>
  );
}

export function SigBox({ title, info }: { title: string; info: SignatoryInfo }) {
  return (
    <View style={s.sigBox}>
      <Text style={s.sigTitle}>{title}</Text>
      <View style={s.sigLine} />
      <Text style={s.sigCaption}>Signature</Text>
      <View style={s.sigDetailRow}>
        <Text style={s.sigDetailLabel}>Name</Text>
        <Text style={s.sigDetailValue}>{info.name || ' '}</Text>
      </View>
      <View style={s.sigDetailRow}>
        <Text style={s.sigDetailLabel}>Designation</Text>
        <Text style={s.sigDetailValue}>{info.designation || ' '}</Text>
      </View>
      <View style={s.sigDetailRow}>
        <Text style={s.sigDetailLabel}>Date</Text>
        <Text style={s.sigDetailValue}> </Text>
      </View>
    </View>
  );
}

export function SignatureGrid({ signatories }: { signatories: { preparedBy: SignatoryInfo; vendor: SignatoryInfo; consultant: SignatoryInfo; pmc: SignatoryInfo; client: SignatoryInfo } }) {
  return (
    <View style={s.sigGrid}>
      <SigBox title="Prepared By" info={signatories.preparedBy} />
      <SigBox title="Vendor" info={signatories.vendor} />
      <SigBox title="Consultant" info={signatories.consultant} />
      <SigBox title="PMC" info={signatories.pmc} />
      <SigBox title="Client" info={signatories.client} />
    </View>
  );
}

export function PdfFooter({ logoDataUri, qrDataUri, generatedAtFormatted }: { logoDataUri: string; qrDataUri: string; generatedAtFormatted: string }) {
  return (
    <View style={s.footer} fixed>
      <Image src={logoDataUri} style={s.footerLogo} />
      <View style={s.footerTextBlock}>
        <Text style={s.footerText}>Generated by AxInfra · {generatedAtFormatted}</Text>
      </View>
      <Text style={s.footerText} render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
      <Image src={qrDataUri} style={[s.footerQr, { marginLeft: 10 }]} />
    </View>
  );
}

export function EmptyTableRow({ message, colSpanWidth = '100%' }: { message: string; colSpanWidth?: string }) {
  return (
    <View style={s.tableRow}>
      <Text style={[s.td, { width: colSpanWidth, color: MUTED }]}>{message}</Text>
    </View>
  );
}
